# Generated by Django 5.1.3 on 2024-11-18 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StlDistrict',
            fields=[
                ('county_district_code', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stl_district',
            },
        ),
        migrations.CreateModel(
            name='StlDisciplineIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('enrollment_grades_k_12', models.IntegerField()),
                ('discipline_incidents', models.IntegerField()),
                ('discipline_alcohol', models.IntegerField()),
                ('discipline_drug', models.IntegerField()),
                ('discipline_other', models.IntegerField()),
                ('discipline_tobacco', models.IntegerField()),
                ('discipline_violence', models.IntegerField()),
                ('discipline_weapon', models.IntegerField()),
                ('discipline_removal_in_schl_susp', models.IntegerField()),
                ('discipline_removal_out_schl_susp', models.IntegerField()),
                ('discipline_removal_expulsion', models.IntegerField()),
                ('discipline_more_10_days', models.IntegerField()),
                ('county_district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnect.stldistrict')),
            ],
            options={
                'db_table': 'stl_discipline_incidents',
                'unique_together': {('year', 'county_district_code')},
            },
        ),
        migrations.CreateModel(
            name='StlDemographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('enrollment_grades_k_12', models.IntegerField()),
                ('january_membership', models.DecimalField(decimal_places=2, max_digits=11)),
                ('lunch_count_free_reduced', models.DecimalField(decimal_places=2, max_digits=11)),
                ('enrollment_asian', models.IntegerField()),
                ('enrollment_asian_pacific_islander', models.IntegerField()),
                ('enrollment_black', models.IntegerField()),
                ('enrollment_hispanic', models.IntegerField()),
                ('enrollment_indian', models.IntegerField()),
                ('enrollment_multiracial', models.IntegerField()),
                ('enrollment_pacific_islander', models.IntegerField()),
                ('enrollment_white', models.IntegerField()),
                ('ell_lep_students_enrolled_k_12', models.IntegerField()),
                ('ell_lep_students_enrolled_pk', models.IntegerField()),
                ('iep_schoolage_childcount', models.IntegerField()),
                ('county_district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnect.stldistrict')),
            ],
            options={
                'db_table': 'stl_demographic',
                'unique_together': {('year', 'county_district_code')},
            },
        ),
        migrations.CreateModel(
            name='StlActScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('act_tests_administered', models.IntegerField()),
                ('graduates', models.IntegerField()),
                ('graduates_with_act_score_above_national_avg', models.IntegerField()),
                ('act_composite_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('act_english_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('act_math_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('act_reading_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('act_science_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('county_district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnect.stldistrict')),
            ],
            options={
                'db_table': 'stl_act_score',
                'unique_together': {('year', 'county_district_code')},
            },
        ),
        migrations.CreateModel(
            name='StlStudentStaffRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('students_per_admin_ratio', models.IntegerField()),
                ('students_per_classrm_tch_ratio', models.IntegerField()),
                ('students_per_teacher_ratio', models.IntegerField()),
                ('county_district_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnect.stldistrict')),
            ],
            options={
                'db_table': 'stl_student_staff_ratio',
                'unique_together': {('year', 'county_district_code')},
            },
        ),
    ]
